### ISSUE TITLE
Failed Package Install with Node 12

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/loop-bench#1]
This package fails to install when using `Node v12.13.0 (npm v6.12.0)`.

``` bash
Ganeshs-MacBook-Pro-2:loop-bench ganesh$ npm i

> sodium-native@2.4.6 install /Users/ganesh/work/loop-bench/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> rdf-canonize-native@1.1.2 install /Users/ganesh/work/loop-bench/node_modules/rdf-canonize-native
> node-gyp rebuild

  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
  CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
  CXX(target) Release/obj.target/urdna2015/lib/native/NQuads.o
  CXX(target) Release/obj.target/urdna2015/lib/native/addon.o
../lib/native/addon.cc:28:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
      ~~~~^
../lib/native/addon.cc:64:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../lib/native/addon.cc:74:27: error: no template named 'Handle'
  Dataset& dataset, const Handle<Array>& datasetArray);
                          ^
../lib/native/addon.cc:77:9: error: no template named 'Handle'
  const Handle<Object>& object,
        ^
../lib/native/addon.cc:96:3: error: use of undeclared identifier 'Handle'
  Handle<Object> object = Handle<Object>::Cast(info[0]);
  ^
../lib/native/addon.cc:96:10: error: 'Object' does not refer to a value
  Handle<Object> object = Handle<Object>::Cast(info[0]);
         ^
/Users/ganesh/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3400:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../lib/native/addon.cc:96:18: error: use of undeclared identifier 'object'
  Handle<Object> object = Handle<Object>::Cast(info[0]);
                 ^
../lib/native/addon.cc:96:27: error: use of undeclared identifier 'Handle'
  Handle<Object> object = Handle<Object>::Cast(info[0]);
                          ^
../lib/native/addon.cc:96:34: error: 'Object' does not refer to a value
  Handle<Object> object = Handle<Object>::Cast(info[0]);
                                 ^
/Users/ganesh/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3400:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../lib/native/addon.cc:96:43: error: no member named 'Cast' in the global namespace
  Handle<Object> object = Handle<Object>::Cast(info[0]);
                                        ~~^
../lib/native/addon.cc:103:3: error: use of undeclared identifier 'Handle'
  Handle<Array> datasetArray =
  ^
../lib/native/addon.cc:103:10: error: 'Array' does not refer to a value
  Handle<Array> datasetArray =
         ^
/Users/ganesh/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3845:17: note: declared here
class V8_EXPORT Array : public Object {
                ^
../lib/native/addon.cc:103:17: error: use of undeclared identifier 'datasetArray'
  Handle<Array> datasetArray =
                ^
../lib/native/addon.cc:104:5: error: use of undeclared identifier 'Handle'
    Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
    ^
../lib/native/addon.cc:104:12: error: 'Array' does not refer to a value
    Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
           ^
/Users/ganesh/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3845:17: note: declared here
class V8_EXPORT Array : public Object {
                ^
../lib/native/addon.cc:104:20: error: no member named 'Cast' in the global namespace
    Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                 ~~^
../lib/native/addon.cc:104:25: error: use of undeclared identifier 'object'
    Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                        ^
../lib/native/addon.cc:117:29: error: use of undeclared identifier 'datasetArray'
  if(!fillDataset(*dataset, datasetArray)) {
                            ^
../lib/native/addon.cc:133:3: error: use of undeclared identifier 'Handle'
  Handle<Object> object = Handle<Object>::Cast(info[0]);
  ^
../lib/native/addon.cc:133:10: error: 'Object' does not refer to a value
  Handle<Object> object = Handle<Object>::Cast(info[0]);
         ^
/Users/ganesh/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3400:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/urdna2015/lib/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ganesh/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/ganesh/.nvm/versions/node/v12.13.0/bin/node" "/Users/ganesh/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ganesh/work/loop-bench/node_modules/rdf-canonize-native
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN loop-bench@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rdf-canonize-native@1.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rdf-canonize-native@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ganesh/.npm/_logs/2019-12-05T04_10_29_978Z-debug.log
Ganeshs-MacBook-Pro-2:loop-bench ganesh$ 

```

**Comment by davidlehn** [comment]
FYI, index20.js has an commented out 'useNative' flag that would use rdf-canonize-native.  Could maybe move that to an optionalDependency until it's fixed.
